# Generated by Django 2.2.6 on 2019-10-03 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Arquivo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=254, verbose_name='Título')),
                ('arquivo', models.FileField(upload_to='', verbose_name='Arquivo')),
            ],
        ),
    ]
